import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import Product from "./models/Product.js";
import ServiceProvider from "./models/ServiceProvider.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, ".env") });

if (!process.env.MONGODB_URI) {
console.error("MONGODB_URI missing in .env");
process.exit(1);
}

await mongoose.connect(process.env.MONGODB_URI);
console.log("Connected to MongoDB for seeding...");

// Clear existing items
await Product.deleteMany({});
await ServiceProvider.deleteMany({});

// Seed Products (30 products total)
const products = await Product.insertMany([
// ===== Original 12 =====
{
name: "Wooden Bed",
category: "Furniture",
description: "Queen size solid wooden bed frame with ergonomic headboard and under-bed storage drawers.",
monthlyRent: 1200,
securityDeposit: 3000,
tenureOptions: [3, 6, 12],
quantity: 15,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
},
{
name: "Double Door Refrigerator",
category: "Appliances",
description: "260L double door frost-free refrigerator with inverter compressor and multi-airflow cooling.",
monthlyRent: 950,
securityDeposit: 2500,
tenureOptions: [3, 6, 12],
quantity: 10,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
},
{
name: "Modern 3-Seater Sofa",
category: "Furniture",
description: "Plush fabric 3-seater living room sofa with deep seating cushions and stain-resistant fabric.",
monthlyRent: 750,
securityDeposit: 2000,
tenureOptions: [3, 6, 12],
quantity: 12,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
},
{
name: "Ergonomic Study Desk",
category: "Furniture",
description: "Minimalist desk with cable management port, built-in drawer, and sturdy steel legs.",
monthlyRent: 450,
securityDeposit: 1200,
tenureOptions: [3, 6, 12],
quantity: 20,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
},
{
name: "High-Back Mesh Chair",
category: "Furniture",
description: "Adjustable height office chair with lumbar support, 3D armrests, and breathable mesh back.",
monthlyRent: 350,
securityDeposit: 1000,
tenureOptions: [3, 6, 12],
quantity: 18,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1505843490701-5be5d1bdfb35?auto=format&fit=crop&w=800&q=80",
},
{
name: "Front-Load Washing Machine",
category: "Appliances",
description: "7kg fully automatic front load washer with steam hygiene, 1200 RPM spin, and quick 15-min wash.",
monthlyRent: 850,
securityDeposit: 2200,
tenureOptions: [3, 6, 12],
quantity: 8,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
},
{
name: "50-Inch 4K Smart LED TV",
category: "Electronics",
description: "Ultra HD 4K Smart TV with Dolby Atmos sound, Netflix/Prime built-in, and voice search remote.",
monthlyRent: 990,
securityDeposit: 2600,
tenureOptions: [3, 6, 12],
quantity: 10,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
},
{
name: "4-Seater Dining Table",
category: "Furniture",
description: "Compact dining set with solid wood table top and four cushioned ergonomic chairs.",
monthlyRent: 850,
securityDeposit: 2300,
tenureOptions: [3, 6, 12],
quantity: 6,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80",
},
{
name: "1.5 Ton Split AC",
category: "Appliances",
description: "5-star energy efficient inverter split air conditioner with copper condenser and dust filters.",
monthlyRent: 1100,
securityDeposit: 2800,
tenureOptions: [3, 6, 12],
quantity: 14,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
},
{
name: "Convection Microwave Oven",
category: "Appliances",
description: "28L oven with microwave, grill, and convection baking capabilities plus 100+ auto-cook menus.",
monthlyRent: 380,
securityDeposit: 900,
tenureOptions: [3, 6, 12],
quantity: 10,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80",
},
{
name: "Smart LED Desk Lamp",
category: "Electronics",
description: "Touch control desk lamp with 5 color temperatures, wireless phone charging pad, and USB-C port.",
monthlyRent: 150,
securityDeposit: 450,
tenureOptions: [3, 6, 12],
quantity: 25,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=800&q=80",
},
{
name: "Compact Mini Fridge",
category: "Appliances",
description: "93L single door mini refrigerator perfect for hostel rooms, home offices, or studio apartments.",
monthlyRent: 450,
securityDeposit: 1100,
tenureOptions: [3, 6, 12],
quantity: 12,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80",
},

// ===== Additional 18 =====
{
name: "Single Bed with Mattress",
category: "Furniture",
description: "Comfortable single bed with orthopedic mattress suitable for students and professionals.",
monthlyRent: 700,
securityDeposit: 1800,
tenureOptions: [3, 6, 12],
quantity: 18,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
},
{
name: "Wardrobe Cabinet",
category: "Furniture",
description: "Spacious 2-door wardrobe with shelves and hanging space.",
monthlyRent: 500,
securityDeposit: 1400,
tenureOptions: [3, 6, 12],
quantity: 15,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
},
{
name: "Bookshelf Rack",
category: "Furniture",
description: "5-tier wooden bookshelf ideal for books, decor, and storage.",
monthlyRent: 250,
securityDeposit: 700,
tenureOptions: [3, 6, 12],
quantity: 22,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
},
{
name: "Coffee Table",
category: "Furniture",
description: "Modern center table with tempered glass top and storage shelf.",
monthlyRent: 220,
securityDeposit: 600,
tenureOptions: [3, 6, 12],
quantity: 20,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
},
{
name: "TV Entertainment Unit",
category: "Furniture",
description: "Stylish TV unit with cabinets and cable management.",
monthlyRent: 450,
securityDeposit: 1200,
tenureOptions: [3, 6, 12],
quantity: 10,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
},
{
name: "Gaming Chair",
category: "Furniture",
description: "Reclining gaming chair with lumbar and neck support.",
monthlyRent: 480,
securityDeposit: 1300,
tenureOptions: [3, 6, 12],
quantity: 12,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1580481072645-022f9a6d8310?auto=format&fit=crop&w=800&q=80",
},
{
name: "Top Load Washing Machine",
category: "Appliances",
description: "6.5kg fully automatic top load washing machine.",
monthlyRent: 650,
securityDeposit: 1700,
tenureOptions: [3, 6, 12],
quantity: 14,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
},
{
name: "Air Cooler",
category: "Appliances",
description: "High-capacity desert air cooler with honeycomb pads.",
monthlyRent: 350,
securityDeposit: 900,
tenureOptions: [3, 6, 12],
quantity: 18,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
},
{
name: "Water Purifier RO",
category: "Appliances",
description: "RO + UV water purifier with mineral enhancer technology.",
monthlyRent: 300,
securityDeposit: 800,
tenureOptions: [3, 6, 12],
quantity: 20,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
},
{
name: "Induction Cooktop",
category: "Appliances",
description: "1800W induction cooktop with touch controls and preset menus.",
monthlyRent: 180,
securityDeposit: 500,
tenureOptions: [3, 6, 12],
quantity: 25,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80",
},
{
name: "Electric Kettle",
category: "Appliances",
description: "1.5L stainless steel electric kettle with auto shut-off.",
monthlyRent: 90,
securityDeposit: 250,
tenureOptions: [3, 6, 12],
quantity: 30,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80",
},
{
name: "Mixer Grinder",
category: "Appliances",
description: "750W mixer grinder with 3 stainless steel jars.",
monthlyRent: 160,
securityDeposit: 450,
tenureOptions: [3, 6, 12],
quantity: 28,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80",
},
{
name: "Laptop 15-inch",
category: "Electronics",
description: "Intel Core i5 laptop with 16GB RAM and 512GB SSD.",
monthlyRent: 1800,
securityDeposit: 5000,
tenureOptions: [3, 6, 12],
quantity: 8,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80",
},
{
name: "Desktop Computer",
category: "Electronics",
description: "Desktop PC with Intel i5 processor, 16GB RAM, and 24-inch monitor.",
monthlyRent: 1500,
securityDeposit: 4200,
tenureOptions: [3, 6, 12],
quantity: 6,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
},
{
name: "24-Inch Monitor",
category: "Electronics",
description: "Full HD IPS monitor suitable for work and gaming.",
monthlyRent: 350,
securityDeposit: 900,
tenureOptions: [3, 6, 12],
quantity: 16,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=800&q=80",
},
{
name: "Bluetooth Soundbar",
category: "Electronics",
description: "120W Bluetooth soundbar with deep bass and HDMI ARC support.",
monthlyRent: 280,
securityDeposit: 700,
tenureOptions: [3, 6, 12],
quantity: 18,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
},
{
name: "Portable Bluetooth Speaker",
category: "Electronics",
description: "Water-resistant portable speaker with 12-hour battery life.",
monthlyRent: 140,
securityDeposit: 400,
tenureOptions: [3, 6, 12],
quantity: 25,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=800&q=80",
},
{
name: "Wi-Fi Router",
category: "Electronics",
description: "Dual-band high-speed Wi-Fi router suitable for home and office.",
monthlyRent: 120,
securityDeposit: 350,
tenureOptions: [3, 6, 12],
quantity: 30,
serviceArea: "All",
available: true,
image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80",
},
]);

// Seed Service Providers
const providers = await ServiceProvider.insertMany([
{
name: "RentEase Express Logistics",
skillType: "Delivery & Setup Specialist",
servicesOffered: ["Same-Day Delivery", "Free Furniture Assembly", "Old Furniture Pickup"],
description: "Primary logistics partner providing doorstep delivery, assembly, and return pickup across urban hubs.",
serviceArea: "Mumbai",
contactEmail: "[logistics.mumbai@rentease.com](mailto:logistics.mumbai@rentease.com)",
active: true,
},
{
name: "HomeCare Repair & Services",
skillType: "Appliance & Furniture Maintenance",
servicesOffered: ["24/7 Appliance Maintenance", "AC Gas Refill & Cleaning", "Sofa Deep Cleaning"],
description: "Certified service technical network specializing in rapid repair and maintenance for rented appliances.",
serviceArea: "Delhi NCR",
contactEmail: "[support.delhi@homecare.com](mailto:support.delhi@homecare.com)",
active: true,
},
{
name: "Urban Living Solutions",
skillType: "Full House Furnishing Provider",
servicesOffered: ["Complete Room Setup", "Interior Layout Assist", "Relocation Support"],
description: "Complete room furniture and electronic rental package specialist for working professionals.",
serviceArea: "Bengaluru",
contactEmail: "[contact@urbanliving.io](mailto:contact@urbanliving.io)",
active: true,
},
]);

console.log(`Successfully inserted ${products.length} products and ${providers.length} service providers!`);
process.exit(0);
