import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import Product from "./models/Product.js";
import ServiceProvider from "./models/ServiceProvider.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, ".env") });

if (!process.env.MONGODB_URI) {
  console.error("MONGODB_URI missing in .env");
  process.exit(1);
}

await mongoose.connect(process.env.MONGODB_URI);
console.log("Connected to MongoDB for seeding clean product images...");

// Clear existing items
await Product.deleteMany({});
await ServiceProvider.deleteMany({});

// Seed Products (30 products with verified high-res Pexels images)
const products = await Product.insertMany([
  {
    name: "Wooden Bed",
    productName: "Wooden Bed",
    category: "Furniture",
    description: "Queen size solid wooden bed frame with ergonomic headboard and under-bed storage drawers.",
    monthlyRent: 1200,
    price: 1200,
    securityDeposit: 3000,
    tenureOptions: [3, 6, 12],
    quantity: 15,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Double Door Refrigerator",
    productName: "Double Door Refrigerator",
    category: "Appliances",
    description: "260L double door frost-free refrigerator with inverter compressor and multi-airflow cooling.",
    monthlyRent: 950,
    price: 950,
    securityDeposit: 2500,
    tenureOptions: [3, 6, 12],
    quantity: 10,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Modern 3-Seater Sofa",
    productName: "Modern 3-Seater Sofa",
    category: "Furniture",
    description: "Plush fabric 3-seater living room sofa with deep seating cushions and stain-resistant fabric.",
    monthlyRent: 750,
    price: 750,
    securityDeposit: 2000,
    tenureOptions: [3, 6, 12],
    quantity: 12,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Ergonomic Study Desk",
    productName: "Ergonomic Study Desk",
    category: "Furniture",
    description: "Minimalist desk with cable management port, built-in drawer, and sturdy steel legs.",
    monthlyRent: 450,
    price: 450,
    securityDeposit: 1200,
    tenureOptions: [3, 6, 12],
    quantity: 20,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "High-Back Mesh Chair",
    productName: "High-Back Mesh Chair",
    category: "Furniture",
    description: "Adjustable height office chair with lumbar support, 3D armrests, and breathable mesh back.",
    monthlyRent: 350,
    price: 350,
    securityDeposit: 1000,
    tenureOptions: [3, 6, 12],
    quantity: 18,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Front-Load Washing Machine",
    productName: "Front-Load Washing Machine",
    category: "Appliances",
    description: "7kg fully automatic front load washer with steam hygiene, 1200 RPM spin, and quick 15-min wash.",
    monthlyRent: 850,
    price: 850,
    securityDeposit: 2200,
    tenureOptions: [3, 6, 12],
    quantity: 8,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "50-Inch 4K Smart LED TV",
    productName: "50-Inch 4K Smart LED TV",
    category: "Electronics",
    description: "Ultra HD 4K Smart TV with Dolby Atmos sound, Netflix/Prime built-in, and voice search remote.",
    monthlyRent: 990,
    price: 990,
    securityDeposit: 2600,
    tenureOptions: [3, 6, 12],
    quantity: 10,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "4-Seater Dining Table",
    productName: "4-Seater Dining Table",
    category: "Furniture",
    description: "Compact dining set with solid wood table top and four cushioned ergonomic chairs.",
    monthlyRent: 850,
    price: 850,
    securityDeposit: 2300,
    tenureOptions: [3, 6, 12],
    quantity: 6,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/3316918/pexels-photo-3316918.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/3316918/pexels-photo-3316918.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "1.5 Ton Split AC",
    productName: "1.5 Ton Split AC",
    category: "Appliances",
    description: "5-star energy efficient inverter split air conditioner with copper condenser and dust filters.",
    monthlyRent: 1100,
    price: 1100,
    securityDeposit: 2800,
    tenureOptions: [3, 6, 12],
    quantity: 14,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/12209772/pexels-photo-12209772.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/12209772/pexels-photo-12209772.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Convection Microwave Oven",
    productName: "Convection Microwave Oven",
    category: "Appliances",
    description: "28L oven with microwave, grill, and convection baking capabilities plus 100+ auto-cook menus.",
    monthlyRent: 380,
    price: 380,
    securityDeposit: 900,
    tenureOptions: [3, 6, 12],
    quantity: 10,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/4686823/pexels-photo-4686823.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/4686823/pexels-photo-4686823.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Smart LED Desk Lamp",
    productName: "Smart LED Desk Lamp",
    category: "Electronics",
    description: "Touch control desk lamp with 5 color temperatures, wireless phone charging pad, and USB-C port.",
    monthlyRent: 150,
    price: 150,
    securityDeposit: 450,
    tenureOptions: [3, 6, 12],
    quantity: 25,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Compact Mini Fridge",
    productName: "Compact Mini Fridge",
    category: "Appliances",
    description: "93L single door mini refrigerator perfect for hostel rooms, home offices, or studio apartments.",
    monthlyRent: 450,
    price: 450,
    securityDeposit: 1100,
    tenureOptions: [3, 6, 12],
    quantity: 12,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/5824883/pexels-photo-5824883.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Single Bed with Mattress",
    productName: "Single Bed with Mattress",
    category: "Furniture",
    description: "Comfortable single bed with orthopedic mattress suitable for students and professionals.",
    monthlyRent: 700,
    price: 700,
    securityDeposit: 1800,
    tenureOptions: [3, 6, 12],
    quantity: 18,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Wardrobe Cabinet",
    productName: "Wardrobe Cabinet",
    category: "Furniture",
    description: "Spacious 2-door wardrobe with shelves and hanging space.",
    monthlyRent: 500,
    price: 500,
    securityDeposit: 1400,
    tenureOptions: [3, 6, 12],
    quantity: 15,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/6782370/pexels-photo-6782370.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/6782370/pexels-photo-6782370.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Bookshelf Rack",
    productName: "Bookshelf Rack",
    category: "Furniture",
    description: "5-tier wooden bookshelf ideal for books, decor, and storage.",
    monthlyRent: 250,
    price: 250,
    securityDeposit: 700,
    tenureOptions: [3, 6, 12],
    quantity: 22,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Coffee Table",
    productName: "Coffee Table",
    category: "Furniture",
    description: "Modern center table with tempered glass top and storage shelf.",
    monthlyRent: 220,
    price: 220,
    securityDeposit: 600,
    tenureOptions: [3, 6, 12],
    quantity: 20,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/8963959/pexels-photo-8963959.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/8963959/pexels-photo-8963959.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "TV Entertainment Unit",
    productName: "TV Entertainment Unit",
    category: "Furniture",
    description: "Stylish TV unit with cabinets and cable management.",
    monthlyRent: 450,
    price: 450,
    securityDeposit: 1200,
    tenureOptions: [3, 6, 12],
    quantity: 10,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/6970069/pexels-photo-6970069.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/6970069/pexels-photo-6970069.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Gaming Chair",
    productName: "Gaming Chair",
    category: "Furniture",
    description: "Reclining gaming chair with lumbar and neck support.",
    monthlyRent: 480,
    price: 480,
    securityDeposit: 1300,
    tenureOptions: [3, 6, 12],
    quantity: 12,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/7862590/pexels-photo-7862590.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/7862590/pexels-photo-7862590.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Top Load Washing Machine",
    productName: "Top Load Washing Machine",
    category: "Appliances",
    description: "6.5kg fully automatic top load washing machine.",
    monthlyRent: 650,
    price: 650,
    securityDeposit: 1700,
    tenureOptions: [3, 6, 12],
    quantity: 14,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Air Cooler",
    productName: "Air Cooler",
    category: "Appliances",
    description: "High-capacity desert air cooler with honeycomb pads.",
    monthlyRent: 350,
    price: 350,
    securityDeposit: 900,
    tenureOptions: [3, 6, 12],
    quantity: 18,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/7195123/pexels-photo-7195123.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/7195123/pexels-photo-7195123.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Water Purifier RO",
    productName: "Water Purifier RO",
    category: "Appliances",
    description: "RO + UV water purifier with mineral enhancer technology.",
    monthlyRent: 300,
    price: 300,
    securityDeposit: 800,
    tenureOptions: [3, 6, 12],
    quantity: 20,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Induction Cooktop",
    productName: "Induction Cooktop",
    category: "Appliances",
    description: "1800W induction cooktop with touch controls and preset menus.",
    monthlyRent: 180,
    price: 180,
    securityDeposit: 500,
    tenureOptions: [3, 6, 12],
    quantity: 25,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/6205523/pexels-photo-6205523.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/6205523/pexels-photo-6205523.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Electric Kettle",
    productName: "Electric Kettle",
    category: "Appliances",
    description: "1.5L stainless steel electric kettle with auto shut-off.",
    monthlyRent: 90,
    price: 90,
    securityDeposit: 250,
    tenureOptions: [3, 6, 12],
    quantity: 30,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1921673/pexels-photo-1921673.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1921673/pexels-photo-1921673.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Mixer Grinder",
    productName: "Mixer Grinder",
    category: "Appliances",
    description: "750W mixer grinder with 3 stainless steel jars.",
    monthlyRent: 160,
    price: 160,
    securityDeposit: 450,
    tenureOptions: [3, 6, 12],
    quantity: 28,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/8805096/pexels-photo-8805096.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/8805096/pexels-photo-8805096.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Laptop 15-inch",
    productName: "Laptop 15-inch",
    category: "Electronics",
    description: "Intel Core i5 laptop with 16GB RAM and 512GB SSD.",
    monthlyRent: 1800,
    price: 1800,
    securityDeposit: 5000,
    tenureOptions: [3, 6, 12],
    quantity: 8,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Desktop Computer",
    productName: "Desktop Computer",
    category: "Electronics",
    description: "Desktop PC with Intel i5 processor, 16GB RAM, and 24-inch monitor.",
    monthlyRent: 1500,
    price: 1500,
    securityDeposit: 4200,
    tenureOptions: [3, 6, 12],
    quantity: 6,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "24-Inch Monitor",
    productName: "24-Inch Monitor",
    category: "Electronics",
    description: "Full HD IPS monitor suitable for work and gaming.",
    monthlyRent: 350,
    price: 350,
    securityDeposit: 900,
    tenureOptions: [3, 6, 12],
    quantity: 16,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Bluetooth Soundbar",
    productName: "Bluetooth Soundbar",
    category: "Electronics",
    description: "120W Bluetooth soundbar with deep bass and HDMI ARC support.",
    monthlyRent: 280,
    price: 280,
    securityDeposit: 700,
    tenureOptions: [3, 6, 12],
    quantity: 18,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1706644/pexels-photo-1706644.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1706644/pexels-photo-1706644.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Portable Bluetooth Speaker",
    productName: "Portable Bluetooth Speaker",
    category: "Electronics",
    description: "Water-resistant portable speaker with 12-hour battery life.",
    monthlyRent: 140,
    price: 140,
    securityDeposit: 400,
    tenureOptions: [3, 6, 12],
    quantity: 25,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    name: "Wi-Fi Router",
    productName: "Wi-Fi Router",
    category: "Electronics",
    description: "Dual-band high-speed Wi-Fi router suitable for home and office.",
    monthlyRent: 120,
    price: 120,
    securityDeposit: 350,
    tenureOptions: [3, 6, 12],
    quantity: 30,
    serviceArea: "All",
    available: true,
    image: "https://images.pexels.com/photos/4218546/pexels-photo-4218546.jpeg?auto=compress&cs=tinysrgb&w=800",
    imgURL: "https://images.pexels.com/photos/4218546/pexels-photo-4218546.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
]);

// Seed Service Providers
const providers = await ServiceProvider.insertMany([
  {
    name: "RentEase Express Logistics",
    skillType: "Delivery & Setup Specialist",
    servicesOffered: ["Same-Day Delivery", "Free Furniture Assembly", "Old Furniture Pickup"],
    description: "Primary logistics partner providing doorstep delivery, assembly, and return pickup across urban hubs.",
    serviceArea: "Mumbai",
    contactEmail: "logistics.mumbai@rentease.com",
    active: true,
  },
  {
    name: "HomeCare Repair & Services",
    skillType: "Appliance & Furniture Maintenance",
    servicesOffered: ["24/7 Appliance Maintenance", "AC Gas Refill & Cleaning", "Sofa Deep Cleaning"],
    description: "Certified service technical network specializing in rapid repair and maintenance for rented appliances.",
    serviceArea: "Delhi NCR",
    contactEmail: "support.delhi@homecare.com",
    active: true,
  },
  {
    name: "Urban Living Solutions",
    skillType: "Full House Furnishing Provider",
    servicesOffered: ["Complete Room Setup", "Interior Layout Assist", "Relocation Support"],
    description: "Complete room furniture and electronic rental package specialist for working professionals.",
    serviceArea: "Bengaluru",
    contactEmail: "contact@urbanliving.io",
    active: true,
  },
]);

console.log(`Successfully re-seeded database with ${products.length} products with verified high-res Pexels images!`);
process.exit(0);
